name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Enable Remote Desktop
      run: |
        # Enable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        # Set a password for the 'runneradmin' user to allow login
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Install OpenSSH Client
      run: Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

    - name: Start SSH tunnel to remote desktop
      run: |
        # Set up the SSH tunnel to forward the RDP port (no pseudo-terminal allocation)
        $env:SSH_COMMAND = "ssh -R 3389:localhost:3389 serveo.net"
        Invoke-Expression $env:SSH_COMMAND
